### ISSUE TITLE
Web service is failing with: No webservice

### ISSUE THREAD

**Issue by PierreSelim** [Commonists/wm_metrics#20]
http://tools.wmflabs.org/wm-metrics/

Copy paste of the error:
No webservice

The URI you have requested, /wm-metrics/, is not currently serviced.
If you have reached this page from somewhere else...

This URI is part of the wm-metrics tool, maintained by Léna, Jean-Frédéric, and PierreSelim.

That tool might not have a web interface, or it may currently be disabled.

If you're pretty sure this shouldn't be an error, you may wish to notify the tool's maintainers (above) about the error and how you ended up here.
If you maintain this tool

You have not enabled a web service for your tool, or it has stopped working because of a fatal error. You may wish to check your logs or common causes for errors in the help documentation.

**Comment by JeanFred** [comment]
```
ssh tools-login.wmflabs.org
become wm-metrics
webservice restart
```

**Comment by PierreSelim** [comment]
Ok this is working now. Thanks JeanFred !
